import type { Product, Transaction } from '@/lib/types';

export const products: Product[] = [
  {
    id: 'prod-001',
    name: 'Banana Prata',
    purchasePrice: 2.5,
    sellingPrice: 4.5,
    stock: 50,
    unit: 'kg',
    category: 'Fruta',
    lowStockThreshold: 10,
  },
  {
    id: 'prod-002',
    name: 'Maçã Fuji',
    purchasePrice: 4.0,
    sellingPrice: 7.0,
    stock: 35,
    unit: 'kg',
    category: 'Fruta',
    lowStockThreshold: 10,
  },
  {
    id: 'prod-003',
    name: 'Laranja Pera',
    purchasePrice: 3.0,
    sellingPrice: 5.0,
    stock: 80,
    unit: 'kg',
    category: 'Fruta',
    lowStockThreshold: 20,
  },
  {
    id: 'prod-004',
    name: 'Abacaxi Pérola',
    purchasePrice: 5.0,
    sellingPrice: 8.0,
    stock: 8,
    unit: 'unidade',
    category: 'Fruta',
    lowStockThreshold: 5,
  },
  {
    id: 'prod-005',
    name: 'Água de Coco 500ml',
    purchasePrice: 4.0,
    sellingPrice: 7.0,
    stock: 15,
    unit: 'unidade',
    category: 'Bebida',
    lowStockThreshold: 5,
  },
  {
    id: 'prod-006',
    name: 'Mandioca Descascada',
    purchasePrice: 3.5,
    sellingPrice: 6.0,
    stock: 20,
    unit: 'kg',
    category: 'Outro',
    lowStockThreshold: 8,
  },
  {
    id: 'prod-007',
    name: 'Ovos Caipira (dúzia)',
    purchasePrice: 8.0,
    sellingPrice: 12.0,
    stock: 12,
    unit: 'unidade',
    category: 'Outro',
    lowStockThreshold: 5,
  },
   {
    id: 'prod-008',
    name: 'Manga Tommy',
    purchasePrice: 3.0,
    sellingPrice: 5.5,
    stock: 40,
    unit: 'kg',
    category: 'Fruta',
    lowStockThreshold: 10,
  },
  {
    id: 'prod-009',
    name: 'Mamão Formosa',
    purchasePrice: 3.5,
    sellingPrice: 6.0,
    stock: 2,
    unit: 'unidade',
    category: 'Fruta',
    lowStockThreshold: 5,
  },
];

export const transactions: Transaction[] = [
  {
    id: 'txn-001',
    type: 'Venda',
    date: '2024-07-20T10:30:00Z',
    items: [
      { product: products[0], quantity: 2, unitPrice: 4.5 },
      { product: products[1], quantity: 1, unitPrice: 7.0 },
    ],
    total: 16.0,
  },
  {
    id: 'txn-002',
    type: 'Venda',
    date: '2024-07-20T11:00:00Z',
    items: [{ product: products[2], quantity: 5, unitPrice: 5.0 }],
    total: 25.0,
  },
  {
    id: 'txn-003',
    type: 'Compra',
    date: '2024-07-19T04:00:00Z',
    items: [
      { product: products[0], quantity: 50, unitPrice: 2.5 },
      { product: products[1], quantity: 40, unitPrice: 4.0 },
    ],
    total: 285.0,
  },
  {
    id: 'txn-004',
    type: 'Descarte',
    date: '2024-07-19T18:00:00Z',
    items: [{ product: products[3], quantity: 2, unitPrice: 5.0 }],
    total: 10.0,
    reason: 'Amassado',
  },
   {
    id: 'txn-005',
    type: 'Venda',
    date: '2024-07-21T12:15:00Z',
    items: [
      { product: products[7], quantity: 3, unitPrice: 5.5 },
    ],
    total: 16.5,
  },
  {
    id: 'txn-006',
    type: 'Venda',
    date: '2024-07-22T09:45:00Z',
    items: [
      { product: products[4], quantity: 2, unitPrice: 7.0 },
      { product: products[6], quantity: 1, unitPrice: 12.0 },
    ],
    total: 26.0,
  },
];
